# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(default=100)),
                ('height', models.IntegerField(default=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('bookmark_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xds_bookmarks.Bookmark')),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xds_bookmarks.Page')),
            ],
        ),
        migrations.AddField(
            model_name='pane',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xds_bookmarks.Tab'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xds_bookmarks.Location'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xds_bookmarks.Bookmark'),
        ),
    ]
